# .streamlit/secrets.toml

# ✅ CORRECTO (incluye /api al final)
BACKEND_URL = "http://localhost:5000/api"

# Tu API Key de OpenRouteService
ORS_API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjdjNDczMzkwZmIzNDQxMGZiNWFiNWE5YjcyMTg1MjI2IiwiaCI6Im11cm11cjY0In0="